language: c

sudo: required

script:
  - bash -ex .travis-ocaml.sh
  - bash -ex .run-test.sh

env:
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.08
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.10

os:
  - linux
